name: Auto approve

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.actor == 'gitlocalize-app[bot]' || github.actor == 'renovate[bot]'
      with:
        github-token: "${{ secrets.ACCESS_TOKEN }}"
